//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Diplom_project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Adress
    {
        public Adress()
        {
            this.purchase = new HashSet<Purchase>();
        }
        public int idAdress { get; set; }
        [Required(ErrorMessage = "Поле {0} має бути заповнено")]
        [StringLength(20, ErrorMessage = "Поле {0} має бути довжиною не менше {2} літер", MinimumLength = 2)]
        [Display(Name = "Місто")]
        public string city { get; set; }

        [Required(ErrorMessage = "Поле {0} має бути заповнено")]
        [StringLength(50, ErrorMessage = "Поле {0} має бути довжиною не менше {2} літер", MinimumLength = 1)]
        [Display(Name = "Адреса")]
        public string apartment { get; set; }

        [Required(ErrorMessage = "Поле {0} має бути заповнено")]
        [StringLength(50, ErrorMessage = "Поле {0} має бути довжиною не менше {2} літер", MinimumLength = 3)]
        [Display(Name = "Регіон")]
        public string region { get; set; }

        [Required(ErrorMessage = "Поле {0} має бути заповнено")]
        [StringLength(20, ErrorMessage = "Поле {0} має бути довжиною не менше {2} літер", MinimumLength = 6)]
        [Display(Name = "Телефон")]
        public string telephone { get; set; }

        [Required(ErrorMessage = "Поле {0} має бути заповнено")]
        [StringLength(10, ErrorMessage = "Поле {0} має бути довжиною не менше {2} літер", MinimumLength = 3)]
        [Display(Name = "Поштовий індекс")]
        public string postindex { get; set; }

        [Required(ErrorMessage = "Поле {0} має бути заповнено")]
        [StringLength(50, ErrorMessage = "Поле {0} має бути довжиною не менше {2} літер", MinimumLength = 3)]
        [Display(Name = "Країна")]
        public string country { get; set; }
        public int Customer_idCustomer { get; set; }

        public virtual Customer customer { get; set; }
        public virtual ICollection<Purchase> purchase { get; set; }
    }
}
