//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodinpurchase
    {
        public int Product_idProduct { get; set; }
        public int Purchase_idPurchase { get; set; }
        public int amount { get; set; }
    
        public virtual Product product { get; set; }
        public virtual Purchase purchase { get; set; }
    }
}
