//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.gemsinprod = new HashSet<Gemsinprod>();
            this.prodinpurchase = new HashSet<Prodinpurchase>();
        }
    
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public double weightProduct { get; set; }
        public string typeProduct { get; set; }
        public int Material_idMaterial { get; set; }
        public double price { get; set; }
        public Nullable<double> size { get; set; }
        public Nullable<int> ProductDiscont_idProductDiscont { get; set; }
        public string imageName { get; set; }
    
        public virtual ICollection<Gemsinprod> gemsinprod { get; set; }
        public virtual Material material { get; set; }
        public virtual ICollection<Prodinpurchase> prodinpurchase { get; set; }
        public virtual Productdiscont productdiscont { get; set; }
    }
}
