//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.prodinpurchase = new HashSet<Prodinpurchase>();
        }
    
        public int idPurchase { get; set; }
        public System.DateTime datePurchase { get; set; }
        public int Customer_idCustomer { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public int Adress_idAdress { get; set; }
    
        public virtual Adress adress { get; set; }
        public virtual Customer customer { get; set; }
        public virtual ICollection<Prodinpurchase> prodinpurchase { get; set; }
    }
}
