//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gem
    {
        public Gem()
        {
            this.gemsinprod = new HashSet<Gemsinprod>();
        }
    
        public int idGem { get; set; }
        public string nameGem { get; set; }
        public Nullable<double> weightGem { get; set; }
        public string formGem { get; set; }
        public string infoGem { get; set; }
    
        public virtual ICollection<Gemsinprod> gemsinprod { get; set; }
    }
}
