//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.product = new HashSet<Product>();
            this.matinwarehouse = new HashSet<Matinwarehouse>();
        }
    
        public int idMaterial { get; set; }
        public string nameMaterial { get; set; }
        public string probe { get; set; }
    
        public virtual ICollection<Product> product { get; set; }
        public virtual ICollection<Matinwarehouse> matinwarehouse { get; set; }
    }
}
