//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matinwarehouse
    {
        public int Material_idMaterial { get; set; }
        public double weight { get; set; }
        public int WarehouseState_idWarehouseState { get; set; }
    
        public virtual Material material { get; set; }
        public virtual Warehousestate warehousestate { get; set; }
    }
}
