//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productdiscont
    {
        public Productdiscont()
        {
            this.product = new HashSet<Product>();
        }
    
        public int idProductDiscont { get; set; }
        public double discountPercent { get; set; }
        public Nullable<double> discountAmount { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateFinish { get; set; }
    
        public virtual ICollection<Product> product { get; set; }
    }
}
